steps:
  # 1 단계 => docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - build

  # 2 단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - push

  # 3 단계 => kubectl set image deployment/mybackend my-backend03-sha256-1=asia.gcr.io/codecamp-backend-379606/my-backend03:6
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/mybackend
      - my-backend03-sha256-1=asia.gcr.io/codecamp-backend-379606/my-backend03:8
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1
