version: "3.7"

services:
  api-gateway:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - stock-service

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth/src:/auth-service/src

  stock-service:
    build:
      context: ./services/stock
      dockerfile: Dockerfile
