version: "3.7"

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/day08/index.js
      - ./phone.js:/day08/phone.js
    ports:
      - 3001:3001

  mu-database:
    image: mongo:5
    ports:
      - 27017:27017
